name = "cachepilot-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
API_KEY = "cp-45c3e0a7610c023041883cc1b64117d8"

[[d1_databases]]
binding = "DB"
database_name = "cachepilot-telemetry"
database_id = "73376d49-3d19-473c-916b-ef67ed7ec86a"
