import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { ArrowLeft } from 'lucide-react';

type LegalPage = 'terms' | 'privacy';

const termsContent = [
  {
    title: 'Terms of Service',
    lastUpdated: 'July 16, 2026',
    sections: [
      {
        heading: '1. Acceptance of Terms',
        text: 'By downloading, installing, or using CachePilot ("the Software"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Software.',
      },
      {
        heading: '2. Description of Service',
        text: 'CachePilot is a desktop application that helps users identify and remove temporary cache files from their Windows PC. The Software operates entirely locally on your device — no data is transmitted to external servers.',
      },
      {
        heading: '3. User Responsibilities',
        text: 'You are responsible for understanding what each cache type does before cleaning it. CachePilot provides plain-language explanations for every cache category, including potential side effects. It is your responsibility to review these explanations before confirming any cleanup action.',
      },
      {
        heading: '4. Data & Privacy',
        text: 'CachePilot does not collect, transmit, or store any personal data on external servers. All scan results, settings, and history are stored locally on your device. No analytics, telemetry, or tracking is performed.',
      },
      {
        heading: '5. Disclaimer of Warranties',
        text: 'The Software is provided "as is" without warranties of any kind. While we strive to make CachePilot safe and accurate, we cannot guarantee that cache cleaning will never cause unintended side effects such as signed-out sessions or reset preferences.',
      },
      {
        heading: '6. Limitation of Liability',
        text: 'In no event shall the developers of CachePilot be liable for any damages arising from the use or inability to use the Software. You are solely responsible for any data loss or system changes resulting from cache cleanup actions.',
      },
      {
        heading: '7. Changes to Terms',
        text: 'We may update these Terms of Service from time to time. Continued use of the Software after changes constitutes acceptance of the new terms.',
      },
      {
        heading: '8. Contact',
        text: 'For questions about these Terms, contact us at support@cachepilot.app.',
      },
    ],
  },
];

const privacyContent = [
  {
    title: 'Privacy Policy',
    lastUpdated: 'July 16, 2026',
    sections: [
      {
        heading: '1. Overview',
        text: 'CachePilot is designed with privacy as a core principle. This Privacy Policy explains how the Software handles your data — and the short answer is: it doesn\'t send any of it anywhere.',
      },
      {
        heading: '2. Data Collection',
        text: 'CachePilot does NOT collect any personal data. There is no analytics, no telemetry, no tracking pixels, and no user identification. The Software does not phone home or communicate with any external servers.',
      },
      {
        heading: '3. Local Storage',
        text: 'All data generated by CachePilot is stored locally on your device in the application\'s data directory. This includes: scan results and history, application settings, and cleanup logs. This data never leaves your computer.',
      },
      {
        heading: '4. File System Access',
        text: 'CachePilot reads cache directories to identify temporary files that can be safely removed. The Software only accesses standard Windows cache locations (e.g., browser caches, temp folders, Windows Update cache) and never accesses personal documents, photos, or other user files.',
      },
      {
        heading: '5. No Third-Party Services',
        text: 'CachePilot does not integrate with any third-party analytics, advertising, or data processing services. There are no SDKs or libraries that transmit data externally.',
      },
      {
        heading: '6. Updates',
        text: 'When CachePilot checks for updates, it contacts GitHub\'s servers to check for new releases. This request does not contain any personal data — only the current version number of the Software.',
      },
      {
        heading: '7. Changes to This Policy',
        text: 'If this Privacy Policy changes, the updated version will be posted on our website. We will not materially reduce your privacy protections without notice.',
      },
      {
        heading: '8. Contact',
        text: 'For privacy-related questions, contact us at support@cachepilot.app.',
      },
    ],
  },
];

function LegalSection({ heading, text }: { heading: string; text: string }) {
  return (
    <div style={{ marginBottom: 28 }}>
      <h3 style={{
        fontSize: 18,
        fontWeight: 700,
        fontFamily: 'var(--font-display)',
        color: '#E8EDF5',
        marginBottom: 10,
      }}>
        {heading}
      </h3>
      <p style={{
        fontSize: 15,
        lineHeight: 1.7,
        color: '#8A94A6',
      }}>
        {text}
      </p>
    </div>
  );
}

export function Legal() {
  const [page, setPage] = useState<LegalPage | null>(null);

  useEffect(() => {
    const check = () => {
      const hash = window.location.hash.replace('#', '');
      if (hash === 'terms' || hash === 'privacy') {
        setPage(hash);
      } else {
        setPage(null);
      }
    };
    check();
    window.addEventListener('hashchange', check);
    return () => window.removeEventListener('hashchange', check);
  }, []);

  if (!page) return null;

  const content = page === 'terms' ? termsContent[0] : privacyContent[0];

  return (
    <section style={{
      minHeight: '100vh',
      padding: '120px 24px 80px',
      maxWidth: 720,
      margin: '0 auto',
    }}>
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <a
          href="#"
          onClick={(e) => {
            e.preventDefault();
            window.location.hash = '';
            setPage(null);
          }}
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 6,
            fontSize: 14,
            fontWeight: 500,
            color: '#4DA3FF',
            textDecoration: 'none',
            marginBottom: 40,
            transition: 'opacity 0.2s',
          }}
          onMouseEnter={(e) => (e.currentTarget.style.opacity = '0.8')}
          onMouseLeave={(e) => (e.currentTarget.style.opacity = '1')}
        >
          <ArrowLeft style={{ width: 16, height: 16 }} />
          Back to home
        </a>

        <h1 style={{
          fontSize: 40,
          fontWeight: 800,
          fontFamily: 'var(--font-display)',
          letterSpacing: '-0.02em',
          marginBottom: 8,
        }}>
          {content.title}
        </h1>

        <p style={{
          fontSize: 14,
          color: '#5A6478',
          marginBottom: 48,
        }}>
          Last updated: {content.lastUpdated}
        </p>

        <div>
          {content.sections.map((section) => (
            <LegalSection key={section.heading} {...section} />
          ))}
        </div>
      </motion.div>
    </section>
  );
}
